/** @type {import('stylelint').Config} */
export default {
    extends: ['stylelint-config-standard'],
    plugins: ['stylelint-order'],
    rules: {
        'property-no-vendor-prefix': [
            true,
            { ignoreProperties: ['-webkit-user-select', '-webkit-backdrop-filter'] },
        ],
        'font-family-name-quotes': null,
        'order/properties-order': [
            // Positioning
            'position',
            'inset',
            'top',
            'right',
            'bottom',
            'left',

            // Box Model
            'box-sizing',
            'margin',
            'margin-block',
            'margin-top',
            'margin-block-start',
            'margin-bottom',
            'margin-block-end',
            'margin-inline',
            'margin-left',
            'margin-inline-start',
            'margin-right',
            'margin-inline-end',
            'padding',
            'padding-block',
            'padding-top',
            'padding-block-start',
            'padding-bottom',
            'padding-block-end',
            'padding-inline',
            'padding-left',
            'padding-inline-start',
            'padding-right',
            'padding-inline-end',
            'width',
            'inline-size',
            'min-width',
            'max-width',
            'min-inline-size',
            'max-inline-size',
            'height',
            'block-size',
            'min-height',
            'max-height',
            'min-block-size',
            'max-block-size',
            'aspect-ratio',
            'border',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-width',
            'border-style',
            'border-color',
            'border-collapse',
            'outline',

            // Background & Color
            'color',
            'background',
            'background-color',
            'background-image',
            'background-size',
            'background-position',
            'background-repeat',
            'border-radius',

            // Layout (flex/grid — display omitted, position depends on value)
            'flex',
            'flex-direction',
            'flex-wrap',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'grid-template-rows',
            'grid-template-columns',
            'grid-template-areas',
            'grid-column',
            'grid-row',
            'grid-area',
            'justify-content',
            'justify-items',
            'justify-self',
            'align-content',
            'align-items',
            'align-self',
            'place-content',
            'place-items',
            'place-self',
            'gap',
            'row-gap',
            'column-gap',

            // Typography
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'line-height',
            'text-align',
            'text-decoration',
            'text-overflow',
            'text-transform',
            'white-space',
            'overflow-wrap',
            'word-break',
            'list-style',

            // Visual
            'box-shadow',
            'opacity',
            'overflow',
            'overflow-x',
            'overflow-y',
            'object-fit',
            'object-position',
            'z-index',

            // Animation
            'animation',
            'transition',
            'transform',
            'view-transition-name',

            // Interaction
            'cursor',
            'pointer-events',
            'user-select',
            '-webkit-user-select',
            'field-sizing',
        ],
    },
    overrides: [
        {
            files: ['mcp/public/**/*.css'],
            rules: {},
        },
    ],
};
